version: '3.1'

networks:
  app-network-public:
    driver: bridge

volumes:
  emails:

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Stori2024!!
      MYSQL_DATABASE: StoriChallenge
    networks:
      - app-network-public
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d

  sendemails:
    build: .
    restart: always
    networks:
      - app-network-public
    depends_on:
      - db
    volumes:
      - ./emailOutput:/opt/emails